services:
  db_local:
    image: postgres:17-alpine3.20
    container_name: db_local
    restart: "no"
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
